### ISSUE TITLE
发现一处XSS漏洞，现在报给谁？

### ISSUE THREAD

**Issue by gomez114** [88250/wide#10]
**请先看[《提问的智慧》](https://ld246.com/article/1536377163156)**，并尝试到[链滴](https://ld246.com)搜寻资料解决问题。

----

### 描述问题

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
你好，请参考这里 https://github.com/88250/wide/security/policy

**Comment by gomez114** [comment]
你好，有在线的环境吗，我想重现问题发给你。我在本地搭建环境没有成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "88250/wide"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 晚上6:17
收件人:&nbsp;"88250/wide"<wide@noreply.github.com&gt;;
抄送:&nbsp;"becky"<604577433@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [88250/wide] 发现一处XSS漏洞，现在报给谁？ (#10)





 
你好，请参考这里 https://github.com/88250/wide/security/policy

**Comment by 88250** [comment]
https://wide.b3log.org
