### ISSUE TITLE
http启动时绑定的地址和端口问题，以及arm架构下docker无法使用nanoCPUs

### ISSUE THREAD

**Issue by avtion** [88250/wide#7]
您好，非常感谢作者的付出，发现三个问题，第一次提Issues，提的不好请见谅。

# 1. 测试环境
Linux raspberrypi 4.19.97-v7l+ armv7l GNU/Linux
go version go1.14.2 linux/arm
Docker Engine Community Version 19.03.8 OS/Arch Linux/arm

# 2. http启动时绑定的地址和端口

`main.go`里面，第160行，绑定的地址和端口没有应用`conf.Wide.Server`获取的数据。

https://github.com/88250/wide/blob/3256f60990d855f5e0aea5f25bb012216bb82bb8/main.go#L158-L163

通过直接修改，成功修复绑定问题。

# 3. Arm架构下，无法使用nanoCPUs
使用的测试平台是树莓派4B，Go源码在编译之后Docker无法正常执行，提示"NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted"，发现原因是在`session/processes.go`的第73行。

https://github.com/88250/wide/blob/3256f60990d855f5e0aea5f25bb012216bb82bb8/session/processes.go#L73

删除`-cpus`参数后Docker成功执行命令。

# 4. Docker Run命令被中断，初次使用无法正常拉取Golang镜像
在初次使用时，Wide需要从DockerHub拉取Golang镜像用于编译源码，但是因为网速的原因，无法在5秒之内拉取镜像，所以命令会被强制中断，具体代码：

https://github.com/88250/wide/blob/3256f60990d855f5e0aea5f25bb012216bb82bb8/session/processes.go#L181-L198

通过提前执行Pull操作可以成功拉取镜像，程序在Wide上也能正常编译。

但是希望能够将Pull的过程和Run的过程分开，可以在程序初始化的过程先判断Golang镜像是否在Docker中保存至本地，避免Run的时候才Pull。

**Comment by 88250** [comment]
2 希望通过 NGINX 反代来实现，server 配置是最终域名，和绑定监听没有关系
3 稍后会去掉 cpu 限制
4 提前拉取一下镜像，懒得改了 :)

感谢反馈！
